"""Generated. Do not edit — run tools/gen_archaeology_strings.py.

Every translatable string in data/archaeology/scripture_in_stone.toml,
mirrored here so xgettext can see it. Nothing imports this module at run
time; it exists to be scanned. `archaeology_bridge` translates the same
strings by passing the TOML's values through `_()`, which resolves against
exactly these msgids.
"""

from i18n import N_


_STRINGS = [
    N_('Scripture in Stone'),
    N_('The Bible and the archaeological record'),
    N_('Scripture was written in a real world of kings, empires, and cities, and that world left traces in the ground. This gallery gathers artifacts that touch the people, places, and events named in the Bible: a victory stele that mentions the house of David, an Assyrian monument that pictures a king of Israel, a Persian cylinder, a stone bearing Pilate\'s name.\n'
       '\n'
       'A note on method. The aim here is evidence, not argument. Each entry describes what the object is and what it attests, and stops there; an inscription can confirm that a king reigned or a governor held office without settling everything the Bible says about him. Objects of doubtful authenticity are left out, and where serious scholars disagree, the disagreement is named. Read in this spirit, these stones are not proofs but witnesses: fragments of the historical ground on which the text stands.'),
    N_('Before the Kingdom'),
    N_('Before Israel appears in any record, its neighbours were already writing, and a few of their texts bear on its earliest story.'),
    N_('The United Monarchy'),
    N_('From the centuries the Bible assigns to Saul, David, and Solomon: the first inscriptions, and the first monumental stones of a kingdom.'),
    N_('The Kingdom Divided'),
    N_('One kingdom had become two, Israel and Judah, as the great powers to the east began to write their names into the record.'),
    N_('Judah, Assyria, and Nineveh'),
    N_('Judah stands alone now, under the growing power of Assyria: a war of empires and a besieged city, recorded by both sides.'),
    N_('The Fall and the Exile'),
    N_('Babylon\'s rise and Jerusalem\'s fall, and the long captivity by the rivers of a foreign land.'),
    N_('Return under Persia'),
    N_('Under the kings of Persia, the road home, and the royal policy that let a scattered people return to rebuild.'),
    N_('Between the Testaments'),
    N_('The centuries between the Testaments, which were not silent at all: Greek kings, the Maccabees, and the scrolls of a waiting people.'),
    N_('The World of Jesus'),
    N_('The Judea of the Gospels in what it left behind: a governor\'s name, a high priest\'s family tomb, the pools and pavements of the city.'),
    N_('The Apostolic World'),
    N_('Out from Jerusalem into the wider world: the cities, courts, and crowds the apostles met across the Roman East.'),
    N_('The Fall of Jerusalem'),
    N_('The great revolt and its end, and the monuments Rome itself raised over the destruction of Jerusalem in AD 70.'),
    N_('Everyday Life'),
    N_('Beneath the kings and the empires lay the ordinary world the Bible takes for granted: its homes and lamps, its presses and weights, its household gods.'),
    N_('The Amarna Letter of Abdi-Heba'),
    N_('Tell el-Amarna, Egypt'),
    N_('14th century BC'),
    N_('Vorderasiatisches Museum, Berlin'),
    N_('Found at Tell el-Amarna, 1887'),
    N_('A letter from Abdi-Heba, ruler of Jerusalem, to the pharaoh of Egypt, some three centuries before David.'),
    N_('He writes the city\'s name Urusalim.'),
    N_('The Merneptah Stele'),
    N_('Thebes, Egypt'),
    N_('c. 1208 BC'),
    N_('Egyptian Museum, Cairo'),
    N_('Excavated at Thebes by Flinders Petrie, 1896'),
    N_('Pharaoh Merneptah\'s victory hymn, about 1208 BC, naming Israel among the peoples of Canaan.'),
    N_('The sign written with “Israel” marks a people, not a place: the earliest mention of Israel outside the Bible.'),
    N_('The Tel Dan Stele'),
    N_('Tel Dan, northern Israel'),
    N_('9th century BC'),
    N_('Israel Museum, Jerusalem'),
    N_('Excavated in situ at Tel Dan, 1993–94'),
    N_('An Aramaic victory stele, most likely of Hazael of Damascus, naming a king of the “House of David” (bytdwd).'),
    N_('Some read bytdwd as a place name, since a word divider would usually stand between “house” and “David”.'),
    N_('Its restored lines claim the deaths of Joram and Ahaziah, which 2 Kings 9 gives to Jehu.'),
    N_('The Eshbaal Inscription'),
    N_('Khirbet Qeiyafa, Judah'),
    N_('c. 1000 BC'),
    N_('Israel Antiquities Authority'),
    N_('Excavated at Khirbet Qeiyafa, 2012'),
    N_('A storage jar incised before firing with the name “Eshbaal son of Beda”, about 1000 BC.'),
    N_('The same name, not the same man: Saul\'s son Eshbaal was not Beda\'s. The name was in use in Saul\'s day.'),
    N_('The Six-Chambered Gate at Gezer'),
    N_('Tel Gezer'),
    N_('10th century BC (debated)'),
    N_('in situ'),
    N_('Excavated in situ at Gezer'),
    N_('A six-chambered city gate at Gezer, one of three alike, with Hazor\'s and Megiddo\'s.'),
    N_('Some date the three gates a century after Solomon.'),
    N_('The Gezer Calendar'),
    N_('Gezer'),
    N_('10th century BC'),
    N_('Istanbul Archaeology Museums'),
    N_('Excavated at Gezer, 1908'),
    N_('A small limestone tablet listing the farming year in early Hebrew letters, 10th century BC.'),
    N_('The Campaign Relief of Shishak'),
    N_('Karnak, Egypt'),
    N_('c. 925 BC'),
    N_('Standing temple relief, Karnak'),
    N_('Pharaoh Sheshonq I\'s relief at Karnak, about 925 BC, listing the towns his army claimed in Canaan.'),
    N_('Jerusalem is not among the names that survive on it.'),
    N_('The Mesha Stele'),
    N_('Dibon, Moab'),
    N_('c. 840 BC'),
    N_('Louvre, Paris'),
    N_('Found at Dhiban, 1868; broken up soon after, its text partly preserved in a paper squeeze'),
    N_('Mesha, king of Moab, tells of his revolt against Israel, naming Omri king of Israel and the God of Israel.'),
    N_('A later reading (Lemaire, 1994) finds “House of David” in line 31, where this 1919 translation has a gap.'),
    N_('The Kurkh Monolith of Shalmaneser III'),
    N_('Üçtepe (Diyarbakır), Turkey'),
    N_('c. 853 BC'),
    N_('British Museum, London'),
    N_('Found at Üçtepe, 1861'),
    N_('Shalmaneser III\'s monument of the battle of Qarqar, 853 BC, naming Ahab among the allied kings.'),
    N_('A Nimrud Ivory'),
    N_('Nimrud (Kalhu), Assyria'),
    N_('9th–8th century BC'),
    N_('Metropolitan Museum of Art'),
    N_('Excavated at Nimrud'),
    N_('A carved ivory inlay from the Assyrian palaces at Nimrud, much of such work Phoenician.'),
    N_('The Black Obelisk of Shalmaneser III'),
    N_('c. 825 BC'),
    N_('Excavated at Nimrud by Layard, 1846'),
    N_('Shalmaneser III\'s obelisk, about 825 BC, showing Jehu of Israel bowed low with his tribute.'),
    N_('It calls him “of the land of Omri”: Jehu was no son of Omri, whose line he ended.'),
    N_('The Gate of Nineveh'),
    N_('Nineveh (Mosul), Iraq'),
    N_('8th–7th century BC'),
    N_('in situ (destroyed 2016)'),
    N_('Excavated in situ at Nineveh'),
    N_('A reconstructed gate of Nineveh with its winged bulls, as they stood before their destruction in 2016.'),
    N_('Sargon II in His Chariot'),
    N_('Khorsabad (Dur-Sharrukin)'),
    N_('c. 710 BC'),
    N_('Iraq Museum, Baghdad'),
    N_('Excavated at Khorsabad, 1840s'),
    N_('A palace relief of Sargon II of Assyria riding to war: the king Isaiah names once.'),
    N_('Some once doubted Sargon had lived; his palace at Khorsabad, found in the 1840s, settled it.'),
    N_('The Lachish Reliefs'),
    N_('Palace of Sennacherib, Nineveh'),
    N_('c. 700–692 BC'),
    N_('Excavated at Nineveh by Layard, 1840s'),
    N_('Sennacherib\'s palace reliefs of his siege and capture of Lachish, 701 BC.'),
    N_('The Taylor Prism of Sennacherib'),
    N_('Nineveh'),
    N_('c. 691 BC'),
    N_('Acquired at Nineveh, 1830'),
    N_('Sennacherib\'s annals of his campaign of 701 BC against Judah: Hezekiah shut up in Jerusalem, and tribute sent after him to Nineveh.'),
    N_('2 Kings 18:14 has three hundred talents of silver; the prism, eight hundred. Both have thirty of gold.'),
    N_('The prism tells of the siege, but not of Jerusalem taken.'),
    N_('The Siloam Inscription'),
    N_('Jerusalem (Siloam tunnel)'),
    N_('c. 701 BC'),
    N_('Found in situ in the Siloam tunnel, 1880'),
    N_('The inscription in Hezekiah\'s tunnel, telling how its two crews of diggers met.'),
    N_('The Bulla of Hezekiah'),
    N_('Jerusalem (Ophel)'),
    N_('c. 700 BC'),
    N_('Excavated at the Ophel, Jerusalem, 2009'),
    N_('A clay sealing stamped with King Hezekiah\'s seal, from the Ophel dig by the Temple Mount, published in 2015.'),
    N_('The Royal Steward Inscription'),
    N_('Silwan, Jerusalem'),
    N_('Found in situ at Silwan, 1870'),
    N_('The lintel of a rock-cut tomb in Silwan, of a royal steward whose name and title fit Shebna.'),
    N_('The name is broken: “…yahu”. His title on the lintel, “over the house”, is the one Isaiah gives Shebna.'),
    N_('The Ketef Hinnom Silver Scrolls'),
    N_('Ketef Hinnom, Jerusalem'),
    N_('c. 600 BC'),
    N_('Excavated in a burial cave at Ketef Hinnom by Gabriel Barkay, 1979'),
    N_('Two silver amulets of about 600 BC, each scratched with the priestly blessing of Numbers 6.'),
    N_('The oldest known copy of words from Scripture, some four centuries older than the Dead Sea Scrolls.'),
    N_('The Babylonian Chronicle'),
    N_('Babylon'),
    N_('c. 550 BC'),
    N_('Acquired from Babylonia (unprovenanced)'),
    N_('A tablet of the Babylonian Chronicle recording Nebuchadnezzar\'s capture of “the city of Judah” in 597 BC.'),
    N_('It gives the day, the second of Adar, and tells of a king seized and another set in his place.'),
    N_('The Lachish Letters'),
    N_('Lachish, Judah'),
    N_('c. 588 BC'),
    N_('Excavated in the gate-room at Lachish by J. L. Starkey, 1935'),
    N_('Letters in ink on potsherds from the gate of Lachish, written as Babylon closed on Judah.'),
    N_('In one the writer can no longer see the signals of Azekah.'),
    N_('The Ishtar Gate of Babylon'),
    N_('6th century BC'),
    N_('Pergamon Museum, Berlin'),
    N_('Excavated at Babylon by Koldewey, 1902–14'),
    N_('A dragon of Marduk in glazed brick from the Ishtar Gate of Nebuchadnezzar\'s Babylon.'),
    N_('The Nabonidus Cylinder'),
    N_('Ur'),
    N_('c. 540 BC'),
    N_('Excavated at Ur'),
    N_('A clay cylinder of Nabonidus, last king of Babylon, closing with a prayer for his son Belshazzar.'),
    N_('Belshazzar ruled for his absent father, which may be why Daniel could be made only third ruler.'),
    N_('The Cyrus Cylinder'),
    N_('after 539 BC'),
    N_('Excavated at Babylon by Rassam, 1879'),
    N_('Cyrus of Persia\'s proclamation after he took Babylon in 539 BC.'),
    N_('It names no Jews: it shows the policy Ezra records, not his decree.'),
    N_('The Behistun Inscription'),
    N_('Behistun, Iran'),
    N_('c. 520 BC'),
    N_('Standing cliff monument, Iran'),
    N_('Darius the Great\'s record of his rise, carved on a cliff in Iran in three languages.'),
    N_('The Heliodorus Stele'),
    N_('Maresha, Israel'),
    N_('178 BC'),
    N_('Unprovenanced; matched to fragments excavated at Maresha'),
    N_('A stele with letters of Seleucus IV and his minister Heliodorus, 178 BC.'),
    N_('Second Maccabees tells of Heliodorus sent to seize the Temple\'s treasury.'),
    N_('A Coin of John Hyrcanus'),
    N_('Judea'),
    N_('135–104 BC'),
    N_('many collections'),
    N_('Hasmonean coinage (many examples known)'),
    N_('A small bronze coin of John Hyrcanus, the Hasmonean priest-ruler, 135–104 BC.'),
    N_('The Great Isaiah Scroll'),
    N_('Qumran, Cave 1'),
    N_('c. 125 BC'),
    N_('Found at Qumran, Cave 1, 1947'),
    N_('A column of the Great Isaiah Scroll from Qumran, about 125 BC, at the song of the suffering servant.'),
    N_('It is a thousand years older than the oldest Hebrew copies of Isaiah known before 1947.'),
    N_('The Pilate Stone'),
    N_('Caesarea Maritima'),
    N_('c. AD 26–36'),
    N_('Excavated in situ at Caesarea, 1961'),
    N_('A dedication from Caesarea that names Pontius Pilate, prefect of Judea.'),
    N_('The stone calls him prefect; the Gospels call him governor.'),
    N_('The Caiaphas Ossuary'),
    N_('Jerusalem'),
    N_('1st century AD'),
    N_('Excavated in a Jerusalem tomb, 1990'),
    N_('A carved limestone bone box from a Jerusalem tomb, found in 1990.'),
    N_('A few question the identification; the name and the priestly family are not in doubt.'),
    N_('The Pool of Bethesda'),
    N_('Excavated in situ, Jerusalem'),
    N_('The excavated twin pool north of the Temple area, once ringed with porticoes.'),
    N_('Scholars still debate how its layout matches John\'s five porches.'),
    N_('The Pool of Siloam'),
    N_('Jerusalem (City of David)'),
    N_('Excavated in situ, Jerusalem, 2004'),
    N_('The stepped edge of the Pool of Siloam, uncovered in 2004 below the City of David.'),
    N_('The Temple Warning Inscription'),
    N_('Jerusalem (Temple Mount)'),
    N_('1st century BC–AD'),
    N_('Found in Jerusalem, 1871'),
    N_('A Greek warning from the Temple\'s barrier, forbidding Gentiles to pass it on pain of death.'),
    N_('Many hear it behind Ephesians 2:14, “the middle wall of partition”.'),
    N_('The Tribute Penny'),
    N_('Lugdunum (Lyon) mint'),
    N_('AD 14–37'),
    N_('Roman imperial coinage (many examples known)'),
    N_('A silver denarius of the emperor Tiberius, the coin of the Gospels\' question of tribute.'),
    N_('Some think the coin shown Jesus more likely a local tetradrachm with Tiberius\' head.'),
    N_('The Arch of Titus'),
    N_('Rome (Forum)'),
    N_('c. AD 81'),
    N_('Standing monument, Rome'),
    N_('Rome\'s arch to Titus, with a relief of the Temple\'s spoils carried in his triumph after AD 70.'),
    N_('The Judaea Capta Coinage'),
    N_('Rome'),
    N_('AD 71'),
    N_('A Roman coin struck across the empire after AD 70 to mark the fall of Judea.'),
    N_('Its legend means “Judea captured”.'),
    N_('The Forum of Philippi'),
    N_('Philippi, Macedonia'),
    N_('Roman era'),
    N_('Excavated by the French School at Athens, from 1914'),
    N_('The forum of Philippi, the Roman colony where Paul founded his first church in Europe.'),
    N_('The Areopagus (Mars Hill)'),
    N_('Athens'),
    N_('Paul\'s visit c. AD 50'),
    N_('Standing site, Athens'),
    N_('Mars Hill, below the Acropolis of Athens, where the city\'s council met.'),
    N_('The Bema at Corinth'),
    N_('Ancient Corinth'),
    N_('Excavated by the American School of Classical Studies, from 1896'),
    N_('The raised platform in Corinth\'s forum from which Roman officials gave judgment.'),
    N_('An inscription at Delphi dates Gallio\'s office: the firmest date in Paul\'s journeys.'),
    N_('The Great Theatre of Ephesus'),
    N_('Ephesus'),
    N_('Excavated by the Austrian Archaeological Institute, from 1895'),
    N_('The great theatre of Ephesus, which held some 25,000 people.'),
    N_('The Temple of Artemis'),
    N_('rebuilt after 356 BC'),
    N_('Site located by John Turtle Wood, 1869'),
    N_('One re-erected column marks the Temple of Artemis at Ephesus, a wonder of the ancient world.'),
    N_('The Erastus Inscription'),
    N_('Excavated in situ at Corinth'),
    N_('A paving stone by Corinth\'s theatre naming Erastus, who laid it at his own expense as aedile.'),
    N_('Its date is disputed, and so is whether this Erastus is Paul\'s.'),
    N_('Ancient Jericho'),
    N_('Tell es-Sultan, Jericho'),
    N_('tower c. 8000 BC'),
    N_('Tower excavated by Kathleen Kenyon, 1952–58'),
    N_('The mound of ancient Jericho, among the oldest towns on earth; its stone tower is millennia older than Joshua.'),
    N_('The dating of its fallen walls is much debated: Garstang placed them about 1400 BC, Kenyon about 1550.'),
    N_('Tel Hazor'),
    N_('Bronze–Iron Age'),
    N_('Excavated by Yigael Yadin, 1955–58; digs continue'),
    N_('Hazor, the largest mound in the land, with a burnt Canaanite city beneath an Israelite one.'),
    N_('The Gate of Megiddo'),
    N_('Tel Megiddo'),
    N_('10th c. BC and later'),
    N_('Excavated by the Oriental Institute of Chicago, 1925–39; digs continue'),
    N_('The chambered gate of Megiddo, the fortress guarding the pass into the Jezreel Valley.'),
    N_('Whether the gate is Solomon\'s is debated. The hill, Har Megiddo, gives Armageddon its name.'),
    N_('The Sanctuary at Arad'),
    N_('Tel Arad'),
    N_('Iron Age'),
    N_('Excavated by Yohanan Aharoni, 1962–67'),
    N_('The desert fortress of Arad, with one of the very few Israelite shrines yet excavated.'),
    N_('Its altar seems to have gone out of use in a reform like Hezekiah\'s.'),
    N_('The Herodian Temple Stones'),
    N_('1st century BC'),
    N_('Standing site, Jerusalem'),
    N_('Herodian stones of the Western Wall, part of Herod\'s retaining wall for the Temple platform.'),
    N_('The Synagogue at Capernaum'),
    N_('Capernaum, Galilee'),
    N_('synagogue 4th–5th c. AD'),
    N_('Excavated in situ, Capernaum'),
    N_('The limestone synagogue of Capernaum, 4th–5th century, on basalt foundations dated to the 1st.'),
    N_('Whether the basalt foundations are the synagogue of Jesus\' day is debated.'),
    N_('A Judean Pillar Figurine'),
    N_('Judah'),
    N_('Excavated; common in Judahite homes'),
    N_('A clay figurine of a woman, of a kind found by hundreds in Judahite houses, 8th–7th century BC.'),
    N_('Their meaning is debated: fertility, protection, or a goddess.'),
    N_('An Israelite Oil Lamp'),
    N_('Levant'),
    N_('c. 900 BC'),
    N_('Metropolitan Museum (acc. 1934); findspot unrecorded'),
    N_('A wheel-made saucer lamp with one edge pinched for the wick, about 900 BC.'),
    N_('The Four-Room House'),
    N_('(modern reconstruction)'),
    N_('Iron Age type'),
    N_('Harvard Semitic Museum'),
    N_('Modern full-scale reconstruction (Harvard Semitic Museum)'),
    N_('A full-size reconstruction of the four-room house, the common Israelite dwelling.'),
    N_('A Rock-Cut Winepress'),
    N_('Judean hills, near Jerusalem'),
    N_('Iron Age–Roman'),
    N_('Rock-cut installation, Judean hills'),
    N_('A winepress cut in the bedrock: a floor for treading above, a vat below.'),
    N_('Judean Scale Weights'),
    N_('Excavated, Judahite sites'),
    N_('A graded set of limestone balance weights, some inscribed with their value.'),
    N_('The pim weight explains 1 Samuel 13:21, where the KJV, not knowing the word, has “a file”.'),
    N_('A Collared-Rim Storage Jar'),
    N_('Shiloh'),
    N_('12th–11th century BC'),
    N_('on display at ancient Shiloh'),
    N_('Excavated at Shiloh'),
    N_('A collared-rim storage jar from Shiloh, of the early Iron Age.'),
    N_('An LMLK Seal Impression'),
    N_('Excavated; thousands known across Judah'),
    N_('A jar handle stamped with the royal LMLK seal and a town\'s name, about 700 BC.'),
    N_('A Herodian Oil Lamp'),
    N_('Michael C. Carlos Museum, Atlanta'),
    N_('Common Herodian-period type'),
    N_('The small wheel-made lamp of the New Testament age.'),
    N_('A drawing of the inscription\'s letters; line 9 carries the phrase bytdwd, \'House of David.\''),
    N_('A closeup of line 27, where the hieroglyphs spell out the name \'Israel.\''),
    N_('The tribute panel up close: the figure prostrate before Shalmaneser is labelled \'Jehu, son of Omri,\' the only contemporary image of a king of Israel.'),
    N_('Line 18 (circled), naming YHWH, the God of Israel, among the spoils Mesha carried off.'),
    N_('Another panel of the same relief: Assyrian siege-ramps and engines storming the walls of Lachish.'),
    N_('The letters read closely: \'[E]RASTVS PRO AED[ILITATE] S[VA] P[ECVNIA] STRAVIT,\' Erastus paving it at his own expense.'),
    N_('Tell (tel)'),
    N_('A mound built up over centuries as a town was rebuilt on its own ruins, layer upon layer: the characteristic site of Near Eastern archaeology.'),
    N_('Stratum'),
    N_('A single layer of occupation within a tell. Reading the layers in order (stratigraphy) is how a site and the objects in it are dated.'),
    N_('In situ'),
    N_('Found in its original place, in a documented archaeological context, as opposed to an object that surfaced on the antiquities market.'),
    N_('Provenance'),
    N_('The recorded history of where an object was found and how it reached its present home. A secure provenance is what separates evidence from a possible forgery.'),
    N_('Stele'),
    N_('An upright stone slab carved with an inscription or relief and set up as a monument, often to mark a victory or a boundary.'),
    N_('Relief'),
    N_('A carving raised from a flat background, as on the palace walls and monuments of Assyria and Egypt.'),
    N_('Cuneiform'),
    N_('Wedge-shaped script pressed into wet clay with a reed stylus, used across Mesopotamia for Akkadian, Sumerian, and other languages.'),
    N_('Ostracon'),
    N_('A potsherd reused as a cheap writing surface for notes, receipts, and letters: the everyday paper of the ancient world, as in the Lachish Letters.'),
    N_('Bulla'),
    N_('A lump of clay pressed over the cord of a rolled document and stamped with a seal, preserving the owner\'s name in miniature.'),
    N_('Epigraphy'),
    N_('The study of ancient inscriptions: their script, language, and dating.'),
    N_('Eponym'),
    N_('An Assyrian official after whom a year was named. The surviving eponym lists give Assyrian chronology its backbone, fixing dates like 853 BC for the battle of Qarqar on the Kurkh Monolith.'),
    N_('Ossuary'),
    N_('A stone box for the reburied bones of the dead, common in and around Jerusalem in the first century AD.'),
    N_('Ashlar'),
    N_('A large building stone squared and finely dressed on its faces, as in the Herodian masonry of the Temple platform.'),
    N_('Bema'),
    N_('A raised platform from which a Roman magistrate gave public judgment, as at Corinth.'),
    N_('Squeeze'),
    N_('A paper impression pressed onto an inscription to record its text. The Mesha Stele is partly known from a squeeze taken before the stone was broken.'),
    N_('The standard sourcebook: the inscriptions gathered here, in scholarly translation.'),
    N_('The careful catalogue behind the lists of biblical figures named in the epigraphic record.'),
    N_('A standard survey of the archaeology of ancient Israel and its neighbours.'),
    N_('A brief, even-handed entry point to the field and its methods.'),
    N_('A wide-ranging scholarly case for the Old Testament\'s standing as history.'),
    N_('An influential critical reading that dates much of the tradition later; worth knowing and weighing against the evidence above.'),
    N_('Their online collections: catalogue entries, with photographs and bibliography, for many of the objects shown here.'),
]
