"""Generated. Do not edit — run tools/gen_archaeology_strings.py.

Every translatable string in data/archaeology/scripture_in_stone.toml,
mirrored here so xgettext can see it. Nothing imports this module at run
time; it exists to be scanned. `archaeology_bridge` translates the same
strings by passing the TOML's values through `_()`, which resolves against
exactly these msgids.
"""

from i18n import N_


_STRINGS = [
    N_('Scripture in Stone'),
    N_('The Bible and the archaeological record'),
    N_('Scripture was written in a real world of kings, empires, and cities, and that world left traces in the ground. This gallery gathers artifacts that touch the people, places, and events named in the Bible: a victory stele that mentions the house of David, an Assyrian monument that pictures a king of Israel, a Persian cylinder, a stone bearing Pilate\'s name.\n'
       '\n'
       'A note on method. The aim here is evidence, not argument. Each entry describes what the object is and what it attests, and stops there; an inscription can confirm that a king reigned or a governor held office without settling everything the Bible says about him. Objects of doubtful authenticity are left out, and where serious scholars disagree, the disagreement is named. Read in this spirit, these stones are not proofs but witnesses: fragments of the historical ground on which the text stands.'),
    N_('Before the Kingdom'),
    N_('Before there was an Israel for the records to name, its neighbours were already writing, and a few of their words reach across to touch its earliest story.'),
    N_('The United Monarchy'),
    N_('From the centuries the Bible assigns to Saul, David, and Solomon: the first inscriptions, and the first monumental stones of a kingdom.'),
    N_('The Kingdom Divided'),
    N_('One kingdom had become two, Israel and Judah, as the great powers to the east began to write their names into the record.'),
    N_('Judah, Assyria, and Nineveh'),
    N_('Judah alone now, in the lengthening shadow of Assyria: a clash of empires and a single besieged city, set down from both sides.'),
    N_('The Fall and the Exile'),
    N_('Babylon\'s rise and Jerusalem\'s fall, and the long captivity by the rivers of a foreign land.'),
    N_('Return under Persia'),
    N_('Under the kings of Persia, the road home, and the royal policy that let a scattered people return to rebuild.'),
    N_('Between the Testaments'),
    N_('The centuries between the Testaments, which were not silent at all: Greek kings, the Maccabees, and the scrolls of a waiting people.'),
    N_('The World of Jesus'),
    N_('The Judea of the Gospels brought down to its stones: a governor\'s name, a high priest\'s bones, the pools and pavements of the city.'),
    N_('The Apostolic World'),
    N_('Out from Jerusalem into the wider world: the cities, courts, and crowds the apostles met across the Roman East.'),
    N_('The Fall of Jerusalem'),
    N_('The great revolt and its end, and the monuments Rome itself raised over the destruction of Jerusalem in AD 70.'),
    N_('Everyday Life'),
    N_('Beneath the kings and the empires lay the ordinary world the Bible takes for granted: its homes and lamps, its presses and weights, its household gods.'),
    N_('The Amarna Letter of Abdi-Heba'),
    N_('Tell el-Amarna, Egypt'),
    N_('14th century BC'),
    N_('Vorderasiatisches Museum, Berlin'),
    N_('Found at Tell el-Amarna, 1887'),
    N_('A cuneiform letter from Abdi-Heba, the ruler of Jerusalem, to the Egyptian pharaoh, written generations before David. It is among the earliest references to Jerusalem (as \'Urusalim\'), and shows the city as a small Canaanite kingdom under Egyptian oversight: the world into which Israel would later come.'),
    N_('The Merneptah Stele'),
    N_('Thebes, Egypt'),
    N_('c. 1208 BC'),
    N_('Egyptian Museum, Cairo'),
    N_('Excavated at Thebes by Flinders Petrie, 1896'),
    N_('A victory stele of the pharaoh Merneptah, listing peoples his armies claimed to have defeated in Canaan. Among them, in hieroglyphs, is the name \'Israel,\' marked as a people rather than a place. It is the earliest mention of Israel found outside the Bible, placing the people in the land in the era of the Judges.'),
    N_('The Tel Dan Stele'),
    N_('Tel Dan, northern Israel'),
    N_('9th century BC'),
    N_('Israel Museum, Jerusalem'),
    N_('Excavated in situ at Tel Dan, 1993–94'),
    N_('A fragmentary basalt victory stele, written in Aramaic, set up by a king of Aram-Damascus. Its lines boast of defeating a \'king of Israel\' and a king of the \'House of David\' (bytdwd). It is the earliest reference outside the Bible to David\'s dynasty: a witness that the line of David was remembered as a real royal house within about a century and a half of his reign.'),
    N_('The Eshbaal Inscription'),
    N_('Khirbet Qeiyafa, Judah'),
    N_('c. 1000 BC'),
    N_('Israel Antiquities Authority'),
    N_('Excavated at Khirbet Qeiyafa, 2012'),
    N_('A large storage jar from a fortified Judahite town, incised before firing with the name \'Eshbaal son of Beda\' in early alphabetic script. Eshbaal is a rare name (its only biblical bearer is a son of King Saul), and the inscription shows it in use, and Judahites writing, in the very era the Bible assigns to Saul and David.'),
    N_('The Six-Chambered Gate at Gezer'),
    N_('Tel Gezer'),
    N_('10th century BC (debated)'),
    N_('in situ'),
    N_('Excavated in situ at Gezer'),
    N_('A monumental city gate at Gezer, one of three nearly identical gates (with Hazor and Megiddo) long linked to a single royal building programme: the cities First Kings says Solomon fortified. The dating is debated, some placing the gates a little later, but they attest a kingdom building on a substantial, centralised scale.'),
    N_('The Gezer Calendar'),
    N_('Gezer'),
    N_('10th century BC'),
    N_('Istanbul Archaeology Museums'),
    N_('Excavated at Gezer, 1908'),
    N_('A small limestone tablet inscribed with a list of the agricultural year: months of sowing, harvest, and pruning. Written in early Hebrew letters, it is among the oldest known texts in the language of the Bible, from the century the Scriptures assign to Solomon, who is said to have rebuilt Gezer.'),
    N_('The Campaign Relief of Shishak'),
    N_('Karnak, Egypt'),
    N_('c. 925 BC'),
    N_('Standing temple relief, Karnak'),
    N_('On the temple wall at Karnak, the pharaoh Sheshonq I left a relief of his campaign into Canaan, with a long list of the towns his army claimed. Sheshonq is widely identified with the biblical Shishak, who, the Bible says, marched against Jerusalem in the fifth year of Rehoboam and carried off the treasures of the Temple.'),
    N_('The Mesha Stele'),
    N_('Dibon, Moab'),
    N_('c. 840 BC'),
    N_('Louvre, Paris'),
    N_('Found at Dhiban, 1868; broken up soon after, its text partly preserved in a paper squeeze'),
    N_('A black basalt victory stele set up by Mesha, king of Moab, recounting his rebellion against Israel. It names \'Omri king of Israel\' and his dynasty, and the God of Israel by the name YHWH; by a contested reading it may also name the \'House of David.\' Second Kings tells the same revolt of Mesha from Israel\'s side.'),
    N_('The Kurkh Monolith of Shalmaneser III'),
    N_('Üçtepe (Diyarbakır), Turkey'),
    N_('c. 853 BC'),
    N_('British Museum, London'),
    N_('Found at Üçtepe, 1861'),
    N_('A monument of the Assyrian king Shalmaneser III recording his campaigns, including the battle of Qarqar in 853 BC against a coalition of western kings. Among the allies it lists \'Ahab the Israelite,\' credited with two thousand chariots: the earliest Assyrian mention of a named king of Israel, who reigns through much of First Kings.'),
    N_('A Nimrud Ivory'),
    N_('Nimrud (Kalhu), Assyria'),
    N_('9th–8th century BC'),
    N_('Metropolitan Museum of Art'),
    N_('Excavated at Nimrud'),
    N_('A finely carved ivory furniture inlay from the Assyrian palaces at Nimrud, where such pieces (much of it Phoenician work, gathered as tribute) survive by the hundred. Ivories like these give substance to the Bible\'s notice of the \'house of ivory\' that Ahab built, and the prophets\' rebukes of those who lounged on \'beds of ivory.\''),
    N_('The Black Obelisk of Shalmaneser III'),
    N_('c. 825 BC'),
    N_('Excavated at Nimrud by Layard, 1846'),
    N_('A black limestone monument recording the campaigns of the Assyrian king Shalmaneser III. One register shows a figure bowing to bring tribute. The cuneiform above names him \'Jehu, son of Omri\': in Assyrian usage, a king of the land of Omri, that is, Israel. It is the only known contemporary image of an Israelite monarch, set against the heavy Assyrian pressure the Bible records in Jehu\'s day.'),
    N_('The Gate of Nineveh'),
    N_('Nineveh (Mosul), Iraq'),
    N_('8th–7th century BC'),
    N_('in situ (destroyed 2016)'),
    N_('Excavated in situ at Nineveh'),
    N_('A reconstructed gate of Nineveh, flanked by the colossal human-headed winged bulls (lamassu) that guarded the Assyrian capital. Nineveh looms large in Scripture: the city Jonah was sent to, and whose violence Nahum condemned. The ancient gate and its bulls were destroyed in 2016; this records them as they stood.'),
    N_('Sargon II in His Chariot'),
    N_('Khorsabad (Dur-Sharrukin)'),
    N_('c. 710 BC'),
    N_('Iraq Museum, Baghdad'),
    N_('Excavated at Khorsabad, 1840s'),
    N_('A palace relief of the Assyrian king Sargon II riding to war. Sargon completed the conquest of Samaria and deported the northern kingdom. Named just once in the Bible and long missing from other records, he was once doubted to have existed at all, until his vast palace at Khorsabad was unearthed. Isaiah names him directly.'),
    N_('The Lachish Reliefs'),
    N_('Palace of Sennacherib, Nineveh'),
    N_('c. 700–692 BC'),
    N_('Excavated at Nineveh by Layard, 1840s'),
    N_('Carved gypsum panels from Sennacherib\'s palace, depicting in documentary detail the Assyrian siege and capture of the Judahite fortress city of Lachish in 701 BC: siege ramps, archers, and files of captives carrying their belongings into exile. The Bible records the same campaign, when Sennacherib \'came up against all the fortified cities of Judah and took them.\''),
    N_('The Taylor Prism of Sennacherib'),
    N_('Nineveh'),
    N_('c. 691 BC'),
    N_('Acquired at Nineveh, 1830'),
    N_('A six-sided clay prism inscribed with the annals of Sennacherib. It records his campaign of 701 BC against Judah, boasting that he shut up Hezekiah \'like a bird in a cage\' in Jerusalem, yet tellingly it never claims to have taken the city. Second Kings tells of the same siege, and of Jerusalem\'s deliverance.'),
    N_('The Siloam Inscription'),
    N_('Jerusalem (Siloam tunnel)'),
    N_('c. 701 BC'),
    N_('Found in situ in the Siloam tunnel, 1880'),
    N_('An inscription carved in the wall of a water tunnel beneath Jerusalem, describing the moment two teams of diggers, working from opposite ends, met in the middle. The tunnel carried water from the Gihon spring inside the city walls: the engineering work the Bible credits to King Hezekiah as he prepared for the Assyrian siege.'),
    N_('The Bulla of Hezekiah'),
    N_('Jerusalem (Ophel)'),
    N_('c. 700 BC'),
    N_('Excavated at the Ophel, Jerusalem, 2009'),
    N_('A clay sealing once pressed over the cord of a document, stamped with the royal seal of \'Hezekiah son of Ahaz, king of Judah,\' above a winged sun-disk. Recovered in controlled excavation near the Temple Mount, it is a personal impression from the administration of the reforming king of Hezekiah\'s chapters.'),
    N_('The Royal Steward Inscription'),
    N_('Silwan, Jerusalem'),
    N_('Found in situ at Silwan, 1870'),
    N_('The carved lintel of a rock-cut tomb in Silwan, opposite the City of David, bearing a Hebrew inscription that warns against disturbing the bones of a royal steward. The official\'s name is broken away, but its surviving ending and his office fit Shebna, the steward whom Isaiah rebukes for hewing himself just such a showy tomb.'),
    N_('The Ketef Hinnom Silver Scrolls'),
    N_('Ketef Hinnom, Jerusalem'),
    N_('c. 600 BC'),
    N_('Excavated in a burial cave at Ketef Hinnom by Gabriel Barkay, 1979'),
    N_('Two tiny strips of silver, rolled up and worn as amulets, from a family tomb on the shoulder of the Hinnom valley. Unrolled, each carried in scratched Hebrew letters the priestly blessing: \'The LORD bless you and keep you.\' Written around 600 BC, on the eve of the exile, they are the oldest surviving words of Scripture, older than the Dead Sea Scrolls by four centuries.'),
    N_('The Babylonian Chronicle'),
    N_('Babylon'),
    N_('c. 550 BC'),
    N_('Acquired from Babylonia (unprovenanced)'),
    N_('A clay tablet from the Babylonian Chronicles, the year-by-year record of Babylon\'s kings. One entry notes how Nebuchadnezzar besieged \'the city of Judah,\' captured it, seized its king, and appointed another: the fall of Jerusalem in 597 BC and the exile of Jehoiachin, set down in plain Babylonian prose beside the account in Second Kings.'),
    N_('The Lachish Letters'),
    N_('Lachish, Judah'),
    N_('c. 588 BC'),
    N_('Excavated in the gate-room at Lachish by J. L. Starkey, 1935'),
    N_('Military dispatches written in ink on potsherds, found in the burnt guardroom of Lachish\'s gate, from the weeks when Nebuchadnezzar\'s army was closing on Judah. In the letter shown here, an officer reports \'we cannot see Azekah\': the signal fires of the neighbouring fortress had gone out. Jeremiah names Lachish and Azekah as the last two fortified cities of Judah left standing.'),
    N_('The Ishtar Gate of Babylon'),
    N_('6th century BC'),
    N_('Pergamon Museum, Berlin'),
    N_('Excavated at Babylon by Koldewey, 1902–14'),
    N_('A dragon of the god Marduk, in glazed and moulded brick from the Ishtar Gate of Babylon: the dazzling capital Nebuchadnezzar rebuilt, and to which Judah was carried into exile. In the book of Daniel the king surveys it in pride: \'Is not this great Babylon, which I have built?\''),
    N_('The Nabonidus Cylinder'),
    N_('Ur'),
    N_('c. 540 BC'),
    N_('Excavated at Ur'),
    N_('A clay cylinder of Nabonidus, last king of Babylon, recording his building works and a prayer for his son. That son is Bel-shar-usur (Belshazzar), who in the book of Daniel holds the feast on the night Babylon falls. The cylinder explains a long-doubted detail: Belshazzar ruled as regent in his father\'s absence, which is why Daniel could be offered only \'third\' place in the kingdom.'),
    N_('The Cyrus Cylinder'),
    N_('after 539 BC'),
    N_('Excavated at Babylon by Rassam, 1879'),
    N_('A clay cylinder inscribed in Babylonian cuneiform after Cyrus the Great of Persia took Babylon. It proclaims his policy of returning displaced peoples and restoring their sanctuaries: the same imperial outlook that, in the biblical account, let the exiles of Judah return from Babylon and rebuild the Temple. The cylinder names no Jews in particular; it attests the policy, not the specific decree.'),
    N_('The Behistun Inscription'),
    N_('Behistun, Iran'),
    N_('c. 520 BC'),
    N_('Standing cliff monument, Iran'),
    N_('High on a cliff in western Iran, Darius the Great proclaimed his rise to power in three languages: the trilingual key that finally let scholars read cuneiform. Darius authorised the rebuilding of the Temple in Jerusalem; this monument shows the very king whose decree, in the book of Ezra, sent the work forward.'),
    N_('The Heliodorus Stele'),
    N_('Maresha, Israel'),
    N_('178 BC'),
    N_('Unprovenanced; matched to fragments excavated at Maresha'),
    N_('A limestone stele inscribed with letters of the Seleucid king Seleucus IV and his minister Heliodorus, appointing officials over the temples of the realm. Heliodorus is remembered in Second Maccabees as the agent sent to seize the treasures of the Temple in Jerusalem, and miraculously driven back.'),
    N_('A Coin of John Hyrcanus'),
    N_('Judea'),
    N_('135–104 BC'),
    N_('many collections'),
    N_('Hasmonean coinage (many examples known)'),
    N_('A small bronze coin of the Hasmonean ruler John Hyrcanus, its Hebrew legend naming \'Yehohanan the High Priest and the Council of the Jews,\' its reverse a double cornucopia. It is a coin of the priest-kings descended from the Maccabean revolt: the independent Jewish state whose story First Maccabees carries toward the New Testament age.'),
    N_('The Great Isaiah Scroll'),
    N_('Qumran, Cave 1'),
    N_('c. 125 BC'),
    N_('Found at Qumran, Cave 1, 1947'),
    N_('A column of the Great Isaiah Scroll from Qumran: here the song of the suffering servant, \'he was wounded for our transgressions.\' Found among the Dead Sea Scrolls in 1947, it is a thousand years older than the previously oldest Hebrew copies of Isaiah, and matches them closely: a witness to how faithfully the text was handed down.'),
    N_('The Pilate Stone'),
    N_('Caesarea Maritima'),
    N_('c. AD 26–36'),
    N_('Excavated in situ at Caesarea, 1961'),
    N_('A limestone block, later reused in the theatre at Caesarea, bearing a Latin dedication that names \'[Pon]tius Pilatus, [Praef]ectus Iuda[ea]e\': Pontius Pilate, prefect of Judea. Found in 1961, it is the only inscription naming Pilate from his own province and time, confirming both his name and his exact title in the years of Jesus\' ministry and trial.'),
    N_('The Caiaphas Ossuary'),
    N_('Jerusalem'),
    N_('1st century AD'),
    N_('Excavated in a Jerusalem tomb, 1990'),
    N_('An ornately carved limestone ossuary (a box for reburied bones) found in a Jerusalem tomb in 1990. Twice inscribed \'Yehosef bar Qayafa\' (Joseph, son of Caiaphas), it is widely identified with the high priest before whom, in the Gospels, Jesus was brought for trial. A minority of scholars question the identification; the name and the priestly family, however, are firmly attested.'),
    N_('The Pool of Bethesda'),
    N_('Excavated in situ, Jerusalem'),
    N_('The excavated remains of a large twin pool, ringed by porticoes, on the north side of Jerusalem\'s Temple area. John\'s Gospel describes the healing of a paralysed man at the pool of Bethesda \'which has five roofed colonnades\': a precise detail, once thought merely symbolic, that the archaeology of the twin pool and its surrounding porches bears out.'),
    N_('The Pool of Siloam'),
    N_('Jerusalem (City of David)'),
    N_('Excavated in situ, Jerusalem, 2004'),
    N_('The stepped stone edge of the Pool of Siloam, uncovered in 2004 at the foot of the City of David: the pool fed by Hezekiah\'s tunnel. In John\'s Gospel Jesus sends a man born blind to wash here, and he returns seeing; these are the steps on which that man, and countless pilgrims, once stood.'),
    N_('The Temple Warning Inscription'),
    N_('Jerusalem (Temple Mount)'),
    N_('1st century BC–AD'),
    N_('Found in Jerusalem, 1871'),
    N_('A limestone block carved with a Greek warning that forbade Gentiles, on pain of death, from passing the barrier into the inner courts of the Temple. It is the very \'dividing wall\' Paul was accused of breaching when he was seized in the Temple, and the image the letter to the Ephesians turns around, declaring that Christ has broken it down.'),
    N_('The Tribute Penny'),
    N_('Lugdunum (Lyon) mint'),
    N_('AD 14–37'),
    N_('Roman imperial coinage (many examples known)'),
    N_('A silver denarius of the emperor Tiberius, his portrait on one side, an enthroned figure on the other. A coin exactly like this is the \'tribute penny\' of the Gospels: shown such a coin and asked about paying taxes, Jesus answers, \'Render to Caesar the things that are Caesar\'s, and to God the things that are God\'s.\''),
    N_('The Arch of Titus'),
    N_('Rome (Forum)'),
    N_('c. AD 81'),
    N_('Standing monument, Rome'),
    N_('On the Arch of Titus in Rome, a relief shows soldiers carrying the spoils of the Jerusalem Temple in triumph (the seven-branched menorah, the table of showbread, the silver trumpets) after the city\'s destruction in AD 70. It is the Temple\'s own furniture, paraded as plunder, in the years after Jesus foretold that not one stone would be left upon another.'),
    N_('The Judaea Capta Coinage'),
    N_('Rome'),
    N_('AD 71'),
    N_('A Roman coin struck to celebrate the crushing of the Jewish revolt: a palm tree, a bound captive, a mourning woman, and the words IUDAEA CAPTA, \'Judea captured.\' Minted across the empire after AD 70, it is Rome\'s own monument to the fall of Jerusalem that the Gospels record Jesus foretelling.'),
    N_('The Forum of Philippi'),
    N_('Philippi, Macedonia'),
    N_('Roman era'),
    N_('Excavated by the French School at Athens, from 1914'),
    N_('The forum of Philippi, the Roman colony in Macedonia where Paul founded his first church on European soil. Acts tells of his arrival, the conversion of Lydia by the riverside, and a night in the city jail: the gospel\'s first steps into Europe.'),
    N_('The Areopagus (Mars Hill)'),
    N_('Athens'),
    N_('Paul\'s visit c. AD 50'),
    N_('Standing site, Athens'),
    N_('The Areopagus, or Mars Hill: the rocky height below the Athenian Acropolis where the city\'s council met. Acts sets here Paul\'s address to the philosophers, taking their altar \'to an unknown god\' as his starting point for the God who \'made the world and everything in it.\''),
    N_('The Bema at Corinth'),
    N_('Ancient Corinth'),
    N_('Excavated by the American School of Classical Studies, from 1896'),
    N_('The forum of ancient Corinth, with the bema, the raised platform from which Roman officials gave judgment. It was before this seat, Acts records, that the proconsul Gallio dismissed the charge brought against Paul. Gallio\'s term of office, dated by an inscription at Delphi, is the firmest anchor for the chronology of Paul\'s mission.'),
    N_('The Great Theatre of Ephesus'),
    N_('Ephesus'),
    N_('Excavated by the Austrian Archaeological Institute, from 1895'),
    N_('The great theatre of Ephesus, which held some 25,000 people. Acts sets here the riot of the silversmiths, who feared Paul\'s preaching would ruin the trade in silver shrines of Artemis and filled the theatre with the chant, \'Great is Artemis of the Ephesians!\''),
    N_('The Temple of Artemis'),
    N_('rebuilt after 356 BC'),
    N_('Site located by John Turtle Wood, 1869'),
    N_('A single re-erected column marks the temple of Artemis at Ephesus, once counted among the seven wonders of the world. The cult of \'Artemis of the Ephesians,\' and the craftsmen who profited from it, form the backdrop to the uproar Paul\'s preaching stirred in the city.'),
    N_('The Erastus Inscription'),
    N_('Excavated in situ at Corinth'),
    N_('A paving stone by the theatre of Corinth, its bronze letters lost but their cut sockets still legible: \'Erastus, in return for his aedileship, laid this at his own expense.\' Many identify this magistrate with the Erastus, \'the city treasurer,\' whom Paul names sending greetings from Corinth, though the identification is not certain.'),
    N_('Ancient Jericho'),
    N_('Tell es-Sultan, Jericho'),
    N_('tower c. 8000 BC'),
    N_('Tower excavated by Kathleen Kenyon, 1952–58'),
    N_('The mound of ancient Jericho (Tell es-Sultan), among the oldest towns on earth. The great stone tower here is Neolithic, millennia older than Joshua. The Bible tells of Jericho\'s walls falling before Israel; the dating of the site\'s destruction layers is much debated, one of the harder places where text and trowel meet.'),
    N_('Tel Hazor'),
    N_('Bronze–Iron Age'),
    N_('Excavated by Yigael Yadin, 1955–58; digs continue'),
    N_('The vast mound of Hazor, the largest tel in the land: in the Bible \'the head of all those kingdoms,\' the Canaanite city Joshua is said to have burned. Excavators have found a destroyed Canaanite city beneath a later Israelite one, fortified with a monumental gate of the type the Bible links to Solomon.'),
    N_('The Gate of Megiddo'),
    N_('Tel Megiddo'),
    N_('10th c. BC and later'),
    N_('Excavated by the Oriental Institute of Chicago, 1925–39; digs continue'),
    N_('The chambered gate of Megiddo, the fortress city guarding the pass into the Jezreel Valley. Here King Josiah fell facing Pharaoh Necho; and the city\'s hill, Har Megiddo, gives its name to Armageddon, the gathering-place of Revelation\'s final battle.'),
    N_('The Sanctuary at Arad'),
    N_('Tel Arad'),
    N_('Iron Age'),
    N_('Excavated by Yohanan Aharoni, 1962–67'),
    N_('The desert fortress of Arad, holding one of the very few Israelite temples yet excavated: a courtyard with a sacrificial altar and a small inner shrine, apparently taken out of use during a religious reform of the kind the Bible credits to Hezekiah, who \'removed the high places\' to centre worship on Jerusalem.'),
    N_('The Herodian Temple Stones'),
    N_('1st century BC'),
    N_('Standing site, Jerusalem'),
    N_('The massive Herodian ashlars of the Western Wall, part of the retaining wall Herod the Great raised to enlarge the Temple platform. These are the kind of stones behind a disciple\'s awe, \'what wonderful stones and what wonderful buildings,\' and Jesus\' reply that not one would be left upon another.'),
    N_('The Synagogue at Capernaum'),
    N_('Capernaum, Galilee'),
    N_('synagogue 4th–5th c. AD'),
    N_('Excavated in situ, Capernaum'),
    N_('The white limestone synagogue of Capernaum, the lakeside town that was the base of Jesus\' Galilean ministry. This building is later (4th–5th century), but it rests on the black basalt foundations of the 1st-century synagogue where, the Gospels say, Jesus taught and healed.'),
    N_('A Judean Pillar Figurine'),
    N_('Judah'),
    N_('Excavated; common in Judahite homes'),
    N_('Small clay figurines of a woman supporting her breasts, mass-produced and found by the hundreds in ordinary Judahite houses. Their exact meaning is debated (fertility, protection, a goddess), but they put a face on the popular household religion the prophets kept condemning, when even in Jerusalem families baked cakes for \'the queen of heaven.\''),
    N_('An Israelite Oil Lamp'),
    N_('Levant'),
    N_('c. 900 BC'),
    N_('Metropolitan Museum (acc. 1934); findspot unrecorded'),
    N_('A simple wheel-made saucer with one edge pinched into a spout to hold the wick: the lamp that lit every Israelite house, burning a little olive oil through the night. Plain and everywhere, it is the lamp of the Psalmist\'s \'lamp unto my feet, and a light unto my path.\''),
    N_('The Four-Room House'),
    N_('(modern reconstruction)'),
    N_('Iron Age type'),
    N_('Harvard Semitic Museum'),
    N_('Modern full-scale reconstruction (Harvard Semitic Museum)'),
    N_('A full-scale modern reconstruction of the \'four-room house,\' the standard Israelite dwelling of the Iron Age: a broad rear room behind three long spaces, the ground floor for animals and storage, the family living above. This is the house behind countless biblical scenes: the home whose doorposts were to carry the words of the Law.'),
    N_('A Rock-Cut Winepress'),
    N_('Judean hills, near Jerusalem'),
    N_('Iron Age–Roman'),
    N_('Rock-cut installation, Judean hills'),
    N_('A winepress hewn from the bedrock: an upper floor where grapes were trodden underfoot, and a lower vat where the juice ran down and gathered. Thousands dot the hills of the land. Isaiah\'s song of the vineyard tells of one being cut. The treading of the press, juice splashing the treader\'s garments red, became Scripture\'s image of both joy and wrath.'),
    N_('Judean Scale Weights'),
    N_('Excavated, Judahite sites'),
    N_('A graded set of polished limestone weights for the balance scale, several inscribed with their value: the shekel and its fractions, the beka, the pim. The standards were never quite uniform, which is why the Law returns so often to honest weights, and why a \'just balance\' and a hidden \'bag of deceitful weights\' could stand for righteousness and fraud themselves.'),
    N_('A Collared-Rim Storage Jar'),
    N_('Shiloh'),
    N_('12th–11th century BC'),
    N_('on display at ancient Shiloh'),
    N_('Excavated at Shiloh'),
    N_('A large collared-rim storage jar: the heavy pithos, named for the ridge at its neck, that became a hallmark of the new highland villages of the early Iron Age, the world of the settlement and the judges. This one comes from Shiloh, where the tabernacle stood and the boy Samuel served; jars like it held the grain, oil, and wine of a household\'s year.'),
    N_('An LMLK Seal Impression'),
    N_('Excavated; thousands known across Judah'),
    N_('A jar handle stamped before firing with a royal seal: a four-winged beetle, the paleo-Hebrew letters l-m-l-k (\'belonging to the king\') above, and a town name below. Thousands are known, almost all from the years around Hezekiah\'s reign. They mark a royal system of storage jars, most likely provisioning Judah\'s towns against the Assyrian onslaught the Bible records him preparing for.'),
    N_('A Herodian Oil Lamp'),
    N_('Michael C. Carlos Museum, Atlanta'),
    N_('Common Herodian-period type'),
    N_('The small wheel-made lamp of the New Testament age, with a short nozzle for the wick and a wide hole for the oil. Lamps like this lit the houses of Jesus\' day: the lamp set on a stand, not under a basket; the lamp a woman lights to sweep her house in search of one lost coin.'),
    N_('A drawing of the inscription\'s letters; line 9 carries the phrase bytdwd, \'House of David.\''),
    N_('A closeup of line 27, where the hieroglyphs spell out the name \'Israel.\''),
    N_('The tribute panel up close: the figure prostrate before Shalmaneser is labelled \'Jehu, son of Omri,\' the only contemporary image of a king of Israel.'),
    N_('Line 18 (circled), naming YHWH, the God of Israel, among the spoils Mesha carried off.'),
    N_('Another panel of the same relief: Assyrian siege-ramps and engines storming the walls of Lachish.'),
    N_('The letters read closely: \'[E]RASTVS PRO AED[ILITATE] S[VA] P[ECVNIA] STRAVIT,\' Erastus paving it at his own expense.'),
    N_('Tell (tel)'),
    N_('A mound built up over centuries as a town was rebuilt on its own ruins, layer upon layer: the characteristic site of Near Eastern archaeology.'),
    N_('Stratum'),
    N_('A single layer of occupation within a tell. Reading the layers in order (stratigraphy) is how a site and the objects in it are dated.'),
    N_('In situ'),
    N_('Found in its original place, in a documented archaeological context, as opposed to an object that surfaced on the antiquities market.'),
    N_('Provenance'),
    N_('The recorded history of where an object was found and how it reached its present home. A secure provenance is what separates evidence from a possible forgery.'),
    N_('Stele'),
    N_('An upright stone slab carved with an inscription or relief and set up as a monument, often to mark a victory or a boundary.'),
    N_('Relief'),
    N_('A carving raised from a flat background, as on the palace walls and monuments of Assyria and Egypt.'),
    N_('Cuneiform'),
    N_('Wedge-shaped script pressed into wet clay with a reed stylus, used across Mesopotamia for Akkadian, Sumerian, and other languages.'),
    N_('Ostracon'),
    N_('A potsherd reused as a cheap writing surface for notes, receipts, and letters: the everyday paper of the ancient world, as in the Lachish Letters.'),
    N_('Bulla'),
    N_('A lump of clay pressed over the cord of a rolled document and stamped with a seal, preserving the owner\'s name in miniature.'),
    N_('Epigraphy'),
    N_('The study of ancient inscriptions: their script, language, and dating.'),
    N_('Eponym'),
    N_('An Assyrian official after whom a year was named. The surviving eponym lists give Assyrian chronology its backbone, fixing dates like 853 BC for the battle of Qarqar on the Kurkh Monolith.'),
    N_('Ossuary'),
    N_('A stone box for the reburied bones of the dead, common in and around Jerusalem in the first century AD.'),
    N_('Ashlar'),
    N_('A large building stone squared and finely dressed on its faces, as in the Herodian masonry of the Temple platform.'),
    N_('Bema'),
    N_('A raised platform from which a Roman magistrate gave public judgment, as at Corinth.'),
    N_('Squeeze'),
    N_('A paper impression pressed onto an inscription to record its text. The Mesha Stele is partly known from a squeeze taken before the stone was broken.'),
    N_('The standard sourcebook: the inscriptions gathered here, in scholarly translation.'),
    N_('The careful catalogue behind the lists of biblical figures named in the epigraphic record.'),
    N_('A standard survey of the archaeology of ancient Israel and its neighbours.'),
    N_('A brief, even-handed entry point to the field and its methods.'),
    N_('A wide-ranging scholarly case for the Old Testament\'s standing as history.'),
    N_('The influential minimalist challenge, which redates much of the tradition; worth knowing and weighing against the evidence above.'),
    N_('Catalogue entries, with photographs and bibliography, for many of the objects shown here.'),
]
