"""Generated. Do not edit — run tools/gen_genealogy_strings.py.

Every translatable string in data/genealogy/genealogy.toml, mirrored here so
xgettext can see it. Nothing imports this module at run time; it exists to be
scanned. `genealogy_bridge` translates the same strings by passing the TOML's
values through `_()` and `C_('person', ...)`, which resolve against exactly
these msgids.
"""

from i18n import N_


def C_(context: str, message: str) -> str:
    """No-op pgettext marker, deliberately named `C_`.

    xgettext is already told `--keyword=C_:1c,2` everywhere this project
    extracts — the meson glib preset and tests/test_translations.py both — and
    a marker under any other name is invisible to all of them. Shadowing the
    real `i18n.C_` is safe here precisely because nothing imports this module
    at run time: it exists to be read by xgettext, never executed.
    """
    return message


_STRINGS = [
    N_('The Book of Generations'),
    N_('The lines the Bible keeps, drawn so they can be held'),
    N_((
     'Scripture keeps lists of names, and readers skip them. They are not\n'
     'filler: they are the spine the rest of the book hangs on, and the\n'
     'writers put them where they did on purpose.\n'
     '\n'
     'Every line below is drawn from the text and cites it. Where a\n'
     'genealogy leaves generations out, the gap is drawn as a gap. Where two\n'
     'writers disagree, both are shown and neither is quietly corrected.')),
    C_('person', 'Adam'),
    N_('man; earth'),
    N_('The first man, and the head Luke traces the line back to.'),
    C_('person', 'Seth'),
    N_('appointed'),
    N_('Given in place of Abel; the line of promise runs through him.'),
    C_('person', 'Enos'),
    N_('mortal man'),
    N_('In his days men began to call on the name of the LORD.'),
    C_('person', 'Cainan'),
    C_('person', 'Kenan'),
    N_('meaning uncertain'),
    N_('Not the \'gotten\' of Cain: the two names are different words.'),
    C_('person', 'Mahalaleel'),
    C_('person', 'Maleleel'),
    N_('praise of God'),
    C_('person', 'Jared'),
    N_('descent'),
    C_('person', 'Enoch'),
    N_('dedicated'),
    N_('He walked with God, and did not die.'),
    C_('person', 'Methuselah'),
    C_('person', 'Mathusala'),
    N_('man of the dart'),
    N_('The longest life recorded; it ends the year of the flood.'),
    C_('person', 'Lamech'),
    N_('His own name is uncertain; the one he gave his son is not. He named Noah for the comfort he hoped for.'),
    C_('person', 'Noah'),
    C_('person', 'Noe'),
    N_('rest; comfort'),
    N_('The flood divides the chapter, and the ages, at him.'),
    C_('person', 'Shem'),
    C_('person', 'Sem'),
    N_('name; renown'),
    N_('The line of promise continues through him.'),
    C_('person', 'Ham'),
    C_('person', 'Japheth'),
    C_('person', 'Arphaxad'),
    C_('person', 'Salah'),
    C_('person', 'Sala'),
    C_('person', 'Eber'),
    C_('person', 'Heber'),
    N_('the region beyond'),
    N_('The name behind "Hebrew".'),
    C_('person', 'Peleg'),
    C_('person', 'Phalec'),
    N_('division'),
    N_('In his days the earth was divided.'),
    C_('person', 'Reu'),
    C_('person', 'Ragau'),
    C_('person', 'Serug'),
    C_('person', 'Saruch'),
    C_('person', 'Nahor'),
    C_('person', 'Nachor'),
    C_('person', 'Terah'),
    C_('person', 'Thara'),
    N_('Left Ur for Canaan and stopped at Haran.'),
    C_('person', 'Abraham'),
    C_('person', 'Abram'),
    N_('father of a multitude'),
    N_('The promise begins here; Matthew opens with him.'),
    C_('person', 'Isaac'),
    N_('laughter'),
    N_('The son of the promise.'),
    C_('person', 'Jacob'),
    C_('person', 'Israel'),
    N_('supplanter'),
    N_('Renamed Israel; his twelve sons are the tribes.'),
    C_('person', 'Leah'),
    N_('Six of the twelve are hers.'),
    C_('person', 'Rachel'),
    N_('Joseph and Benjamin.'),
    C_('person', 'Bilhah'),
    N_('Rachel\'s handmaid.'),
    C_('person', 'Zilpah'),
    N_('Leah\'s handmaid.'),
    C_('person', 'Reuben'),
    C_('person', 'Simeon'),
    C_('person', 'Levi'),
    C_('person', 'Issachar'),
    C_('person', 'Zebulun'),
    C_('person', 'Joseph'),
    C_('person', 'Benjamin'),
    C_('person', 'Dan'),
    C_('person', 'Naphtali'),
    C_('person', 'Gad'),
    C_('person', 'Asher'),
    C_('person', 'Judah'),
    C_('person', 'Juda'),
    C_('person', 'Judas'),
    N_('praise'),
    N_('The royal line runs through him, not through the firstborn.'),
    C_('person', 'Phares'),
    C_('person', 'Pharez'),
    C_('person', 'Perez'),
    N_('a breach'),
    N_('Born of Tamar; his twin\'s hand came out first, and he was born first anyway.'),
    C_('person', 'Esrom'),
    C_('person', 'Hezron'),
    C_('person', 'Aram'),
    C_('person', 'Ram'),
    C_('person', 'Aminadab'),
    C_('person', 'Amminadab'),
    C_('person', 'Naasson'),
    C_('person', 'Nahshon'),
    C_('person', 'Salmon'),
    C_('person', 'Booz'),
    C_('person', 'Boaz'),
    N_('Redeemed Ruth, and so stands in the line.'),
    C_('person', 'Obed'),
    C_('person', 'Jesse'),
    C_('person', 'David'),
    N_('Both genealogies run through him, and part immediately after.'),
    C_('person', 'Thamar'),
    C_('person', 'Tamar'),
    N_('Matthew names her first of the four women.'),
    C_('person', 'Rachab'),
    C_('person', 'Rahab'),
    N_('Taken since the early church for Rahab of Jericho, though Matthew does not say so; he puts her in the line of the Messiah.'),
    C_('person', 'Ruth'),
    N_('A Moabitess; her book exists to end on this genealogy.'),
    C_('person', 'the wife of Uriah'),
    C_('person', 'Bathsheba'),
    C_('person', 'Bath-sheba'),
    C_('person', 'the wife of Urias'),
    N_('Matthew will not give her name here — he names the wrong that was done to her.'),
    C_('person', 'Mary'),
    N_('The line breaks its own grammar at her: Jesus is born of her, not begotten.'),
    C_('person', 'Solomon'),
    C_('person', 'Roboam'),
    C_('person', 'Abia'),
    C_('person', 'Asa'),
    C_('person', 'Josaphat'),
    C_('person', 'Joram'),
    N_('Matthew jumps three generations after him.'),
    C_('person', 'Ozias'),
    C_('person', 'Uzziah'),
    C_('person', 'Azariah'),
    N_('Called Azariah in 1 Chr 3:12 — one man, two names.'),
    C_('person', 'Joatham'),
    C_('person', 'Achaz'),
    C_('person', 'Ezekias'),
    C_('person', 'Manasses'),
    C_('person', 'Amon'),
    C_('person', 'Josias'),
    C_('person', 'Josiah'),
    N_('Matthew skips his son Jehoiakim.'),
    C_('person', 'Jechonias'),
    C_('person', 'Jeconiah'),
    C_('person', 'Jehoiachin'),
    C_('person', 'Coniah'),
    N_('The exile falls in his lifetime.'),
    C_('person', 'Salathiel'),
    N_('Matthew and Luke give him different fathers.'),
    C_('person', 'Zorobabel'),
    N_('The last name the two lists share before Joseph.'),
    C_('person', 'Abiud'),
    C_('person', 'Eliakim'),
    C_('person', 'Azor'),
    C_('person', 'Sadoc'),
    C_('person', 'Achim'),
    C_('person', 'Eliud'),
    C_('person', 'Eleazar'),
    C_('person', 'Matthan'),
    C_('person', 'Ahaziah'),
    N_('Named by 1 Chr 3, passed over by Matthew.'),
    C_('person', 'Joash'),
    C_('person', 'Amaziah'),
    C_('person', 'Jehoiakim'),
    N_('Matthew\'s name for Joseph\'s father.'),
    N_('Matthew traces the line to him; Luke names a different father.'),
    C_('person', 'Jesus'),
    C_('person', 'Heli'),
    N_('Luke\'s name for Joseph\'s father.'),
    C_('person', 'Nathan'),
    N_('Luke leaves the throne line here and follows him.'),
    C_('person', 'Matthat'),
    C_('person', 'Melchi'),
    C_('person', 'Janna'),
    C_('person', 'Mattathias'),
    C_('person', 'Amos'),
    C_('person', 'Naum'),
    C_('person', 'Esli'),
    C_('person', 'Nagge'),
    C_('person', 'Maath'),
    C_('person', 'Semei'),
    C_('person', 'Joanna'),
    C_('person', 'Rhesa'),
    C_('person', 'Neri'),
    C_('person', 'Addi'),
    C_('person', 'Cosam'),
    C_('person', 'Elmodam'),
    C_('person', 'Er'),
    C_('person', 'Jose'),
    C_('person', 'Eliezer'),
    C_('person', 'Jorim'),
    C_('person', 'Jonan'),
    C_('person', 'Melea'),
    C_('person', 'Menan'),
    C_('person', 'Mattatha'),
    N_('Luke names a Cainan the Hebrew of Genesis 11 does not; the Septuagint does.'),
    C_('person', 'God'),
    N_('Ahaziah, Joash and Amaziah stand between them in Chronicles.'),
    N_('Chronicles puts Jehoiakim between them.'),
    N_('Matthew stops saying "begat": Jesus is born of Mary, not begotten of Joseph.'),
    N_('Luke writes "as was supposed", and the chart keeps the qualifier.'),
    N_('Luke ends not at a patriarch but at God; it is a claim, not a link.'),
    N_('From Adam to Noah'),
    N_('The ten before the flood'),
    N_('One name a generation for ten generations, each with a number attached. Read as a list it is inert; read as a field of overlapping lives it is astonishing.'),
    N_('Genesis 5'),
    N_('Ten lives, laid on one axis'),
    N_('Genesis 5, reckoned in years from Adam'),
    N_('Every figure here is arithmetic on Genesis 5:3–32, and the arithmetic assumes what the text does not state: that the ten follow one another with no gap. Read that way, two things fall out that no list can show — these ten lives overlap almost completely, and Methuselah\'s nine hundred and sixty-nine years run out in the year the flood comes. The years are a reckoning, not a date the Bible gives.'),
    N_('From Shem to Abraham'),
    N_('The ten after the flood'),
    N_('The same shape as Genesis 5, and the lifespans fall away as it runs — from Shem\'s six hundred years to Terah\'s two hundred and five.'),
    N_('Genesis 11:10–26'),
    N_('The house of Jacob'),
    N_('Four mothers, twelve sons'),
    N_('Drawn father-only, this is a list of twelve names. Drawn with the mothers, it is the reason the tribes are grouped the way they are for the rest of the Bible.'),
    N_('Genesis 35:23–26'),
    N_('The line Ruth ends on'),
    N_('Ten names, from Perez to David'),
    N_('The book of Ruth exists to arrive here. The same ten men appear in Matthew 1 under their Greek names — Perez is Phares, Hezron is Esrom, Boaz is Booz.'),
    N_('Ruth 4:18–22'),
    N_('Matthew\'s genealogy'),
    N_('Abraham to the Christ, in three sets of fourteen'),
    N_('Matthew counts his own list out loud in 1:17, and his list also passes over four kings Chronicles names. Both facts are drawn here — the bands are his count, the dashed edges are the omissions — and the chart does not say the one caused the other. Ancient genealogy omits generations as a matter of course, and "begat" can span them; the fourteens are also read as a mnemonic, and as the numerical value of David\'s name.'),
    N_('Matthew 1:1–17'),
    N_('Luke\'s genealogy'),
    N_('Jesus back to Adam, and past him'),
    N_('Luke runs the other way — from Jesus backwards — and does not stop at Abraham. He ends at Adam, and then at God, which is a claim rather than a link. Luke gives the older names in their Greek forms — Saruch for Serug, Ragau for Reu, Noe for Noah; one spelling is kept per man here so the two lists can be laid side by side, and either form finds him.'),
    N_('Luke 3:23–38'),
    N_('Matthew and Luke, side by side'),
    N_('Where the two lists touch, and where they part'),
    N_('Both trace Jesus through David. They agree at David, at Shealtiel and Zerubbabel, and at Joseph — and nowhere in between. This chart states that and stops; the classical answers are set out below it, and none of them is chosen here.'),
    N_('Luke gives Mary\'s line'),
    N_('On this reading Matthew traces Joseph\'s descent and Luke traces Mary\'s, with Heli as her father and Joseph named as his son by marriage. It accounts for the two fathers of Joseph directly.'),
    N_('Annius of Viterbo (1490s); widely held since, and the common answer in modern evangelical commentary.'),
    N_('Luke\'s text names Joseph, not Mary, and the reading has to supply the step.'),
    N_('Levirate marriage'),
    N_('A man dying childless had his brother raise up offspring in his name (Deut 25:5–6), so one man can have a legal father and a biological one. Africanus has Heli and Jacob as half-brothers by one mother: Heli died childless, Jacob raised up seed to him, and Joseph is son of Jacob by nature and of Heli by law.'),
    N_('Julius Africanus, in a letter preserved by Eusebius, Church History I.7 (3rd century).'),
    N_('It requires a levirate marriage the text nowhere records.'),
    N_('Legal throne versus natural descent'),
    N_('Matthew follows the royal succession — who held or had claim to the throne — while Luke follows physical descent. The two diverge after David because a throne passes by law and blood passes by birth.'),
    N_('Widely held among Protestant interpreters; set out at length by J. Gresham Machen, The Virgin Birth of Christ (1930).'),
    N_('It explains the shape of the difference better than it explains the two named fathers.'),
]
