# Curated links for the Athanasian Creed (Quicunque vult), 2026-09-30.
# 42 verses as the 1662 Prayer Book prints them; the Latin is Schaff's (44 verses:
# 1662 verse 39 = Latin 39-40, 40 = Latin 41-42). Kinds and stems as in apostles_data.

TITLE = "The Athanasian Creed"
ORIG = "la"

WARN = ("These warnings split the Church of England in the 1860s and 1870s, and the Episcopal "
        "Church in the United States never used this creed in worship. The verses show where "
        "Scripture itself joins salvation to faith.")
DESCENT = ("“Descended into hell” is disputed; see the Apostles' Creed, article 5, for the ways "
           "churches read it.")

L = [
 # (n, English, Latin, stems, links, extra)
 (1, "Whosoever will be saved: before all things it is necessary that he hold the Catholick Faith.",
  "Quicunque vult salvus esse: ante omnia opus est, ut teneat catholicam fidem.", "salv tene fide",
  [("t", "Hebrews 11:6"), ("t", "Jude 1:3"), ("t", "Acts 4:12")],
  {"note": WARN, "coined": [("catholicam", "catholic, “universal”")]}),
 (2, "Which Faith except every one do keep whole and undefiled: without doubt he shall perish everlastingly.",
  "Quam nisi quisque integram inviolatamque servaverit: absque dubio in æternum peribit.", "serv peri aetern",
  [("t", "John 3:18"), ("t", "John 3:36"), ("t", "2 Timothy 1:13")], {"note": WARN}),
 (3, "And the Catholick Faith is this: That we worship one God in Trinity, and Trinity in Unity;",
  "Fides autem catholica hæc est: ut unum Deum in Trinitate, et Trinitatem in Unitate veneremur;", "fide unus unum deus deum",
  [("w", "Deuteronomy 6:4"), ("t", "Matthew 28:19"), ("t", "2 Corinthians 13:14"), ("t", "1 Corinthians 8:4")],
  {"coined": [("Trinitate", "Trinity"), ("catholica", "catholic")],
   "note": "“Trinity” is not a Bible word; Tertullian used it in Latin about 200. The creed uses it for what Matthew 28:19 names: one name, three Persons."}),
 (4, "Neither confounding the Persons: nor dividing the Substance.",
  "Neque confundentes personas: neque substantiam separantes.", "person substant",
  [("w", "Hebrews 1:3"), ("t", "Matthew 3:16-17"), ("t", "John 10:30"), ("t", "John 14:16")], {}),
 (5, "For there is one Person of the Father, another of the Son: and another of the Holy Ghost.",
  "Alia est enim persona Patris: alia Filii: alia Spiritus Sancti.", "patr fili spirit sanct",
  [("t", "Matthew 3:16-17"), ("t", "John 15:26"), ("t", "2 Corinthians 13:14"), ("t", "John 14:16")], {}),
 (6, "But the Godhead of the Father, of the Son, and of the Holy Ghost, is all one: the Glory equal, the Majesty co-eternal.",
  "Sed Patris et Filii et Spiritus Sancti una est divinitas: æqualis gloria, coæterna majestas.", "divinit gloria maiest",
  [("w", "Colossians 2:9"), ("t", "Matthew 28:19"), ("t", "John 5:23"), ("t", "John 17:5")],
  {"coined": [("coæterna", "co-eternal")]}),
 (7, "Such as the Father is, such is the Son: and such is the Holy Ghost.",
  "Qualis Pater: talis Filius: talis et Spiritus Sanctus.", "pater patr fili",
  [("t", "John 5:19"), ("t", "John 14:9"), ("t", "John 16:15")], {}),
 (8, "The Father uncreate, the Son uncreate: and the Holy Ghost uncreate.",
  "Increatus Pater: increatus Filius: increatus et Spiritus Sanctus.", "",
  [("t", "Psalms 90:2"), ("t", "John 1:3"), ("t", "Colossians 1:17"), ("t", "Hebrews 9:14")],
  {"coined": [("Increatus", "uncreate, “uncreated”")]}),
 (9, "The Father incomprehensible, the Son incomprehensible: and the Holy Ghost incomprehensible.",
  "Immensus Pater: immensus Filius: immensus et Spiritus Sanctus.", "immens",
  [("t", "1 Kings 8:27"), ("t", "Jeremiah 23:24"), ("t", "Psalms 139:7"), ("t", "Matthew 28:20")],
  {"note": "The Latin immensus means “without measure”: not held within any place. The 1662 “incomprehensible” carries that older sense."}),
 (10, "The Father eternal, the Son eternal: and the Holy Ghost eternal.",
  "Æternus Pater: æternus Filius: æternus et Spiritus Sanctus.", "aetern",
  [("w", "Romans 16:26"), ("t", "Hebrews 9:14"), ("t", "Psalms 90:2"), ("t", "John 8:58"), ("t", "Revelation 1:8")], {}),
 (11, "And yet they are not three eternals: but one eternal.",
  "Et tamen non tres æterni: sed unus æternus.", "aetern unus",
  [("t", "Deuteronomy 6:4"), ("t", "1 Timothy 1:17")], {}),
 (12, "As also there are not three incomprehensibles, nor three uncreated: but one uncreated, and one incomprehensible.",
  "Sicut non tres increati: nec tres immensi: sed unus increatus: et unus immensus.", "immens unus",
  [("t", "1 Kings 8:27"), ("t", "Isaiah 44:6")], {"coined": [("increatus", "uncreated")]}),
 (13, "So likewise the Father is Almighty, the Son Almighty: and the Holy Ghost Almighty.",
  "Similiter omnipotens Pater: omnipotens Filius: omnipotens et Spiritus Sanctus.", "omnipot",
  [("w", "2 Corinthians 6:18"), ("w", "Revelation 1:8"), ("t", "Matthew 28:18"), ("t", "Luke 1:35"), ("t", "Romans 15:19")], {}),
 (14, "And yet they are not three Almighties: but one Almighty.",
  "Et tamen non tres omnipotentes: sed unus omnipotens.", "omnipot",
  [("w", "Genesis 17:1"), ("w", "Revelation 19:6")], {}),
 (15, "So the Father is God, the Son is God: and the Holy Ghost is God.",
  "Ita Deus Pater: Deus Filius: Deus et Spiritus Sanctus.", "deus deum dei",
  [("t", "1 Corinthians 8:6"), ("w", "John 1:1"), ("t", "John 20:28"), ("t", "Acts 5:3-4"), ("t", "Titus 2:13")], {}),
 (16, "And yet they are not three Gods: but one God.",
  "Et tamen non tres dii: sed unus est Deus.", "unus deus",
  [("w", "Deuteronomy 6:4"), ("w", "1 Corinthians 8:4"), ("w", "James 2:19"), ("t", "Isaiah 45:5")], {}),
 (17, "So likewise the Father is Lord, the Son Lord: and the Holy Ghost Lord.",
  "Ita Dominus Pater: Dominus Filius: Dominus et Spiritus Sanctus.", "domin pater patr spirit",
  [("w", "Matthew 11:25"), ("w", "Philippians 2:11"), ("w", "2 Corinthians 3:17")], {}),
 (18, "And yet not three Lords: but one Lord.",
  "Et tamen non tres domini: sed unus est Dominus.", "unus domin",
  [("w", "Ephesians 4:5"), ("w", "Deuteronomy 6:4"), ("t", "1 Corinthians 8:6")], {}),
 (19, "For like as we are compelled by the Christian verity: to acknowledge every Person by himself to be God and Lord;",
  "Quia sicut singulatim unamquamque personam Deum ac Dominum confiteri, Christiana veritate compellimur:", "deus deum domin confit",
  [("w", "John 20:28"), ("t", "Acts 5:3-4"), ("t", "Philippians 2:11")], {}),
 (20, "So are we forbidden by the Catholick Religion: to say there be three Gods, or three Lords.",
  "Ita tres deos, aut tres dominos dicere, catholica religione prohibemur.", "",
  [("t", "Exodus 20:3"), ("t", "Isaiah 44:6"), ("t", "1 Corinthians 8:5-6")], {"coined": [("catholica", "catholic")]}),
 (21, "The Father is made of none: neither created, nor begotten.",
  "Pater a nullo est factus: nec creatus, nec genitus.", "",
  [("t", "1 Corinthians 8:6"), ("t", "Psalms 90:2"), ("t", "John 5:26")], {}),
 (22, "The Son is of the Father alone: not made, nor created, but begotten.",
  "Filius a Patre solo est: non factus, nec creatus: sed genitus.", "patr genit genui",
  [("w", "John 1:14"), ("w", "John 1:18"), ("t", "John 1:3"), ("f", "Psalms 2:7"), ("f", "Micah 5:2")], {}),
 (23, "The Holy Ghost is of the Father and of the Son: neither made, nor created, nor begotten, but proceeding.",
  "Spiritus Sanctus a Patre et Filio: non factus, nec creatus, nec genitus: sed procedens.", "spirit patr proced",
  [("w", "John 15:26"), ("t", "Galatians 4:6", "Cited by the West."), ("t", "John 16:7", "Cited by the West."), ("t", "Romans 8:9")],
  {"disputed": True, "disp_en": "and of the Son", "disp_orig": "et Filio",
   "note": "The Latin says “of the Father and of the Son”. This creed was written in the West; the Orthodox, who confess that the Spirit proceeds from the Father (John 15:26), do not use it."}),
 (24, "So there is one Father, not three Fathers; one Son, not three Sons: one Holy Ghost, not three Holy Ghosts.",
  "Unus ergo Pater, non tres patres: unus Filius, non tres filii: unus Spiritus Sanctus, non tres spiritus sancti.", "unus pater spirit",
  [("w", "Ephesians 4:4-6"), ("t", "1 Corinthians 12:4-6")], {}),
 (25, "And in this Trinity none is afore, or after other: none is greater, or less than another;",
  "Et in hac Trinitate nihil prius, aut posterius: nihil majus, aut minus.", "",
  [("t", "John 1:1"), ("t", "Philippians 2:6"), ("t", "John 5:18"),
   ("t", "John 14:28", "“My Father is greater than I”: the creed reads it of his manhood (verse 33).")],
  {"coined": [("Trinitate", "Trinity")]}),
 (26, "But the whole three Persons are co-eternal together: and co-equal.",
  "Sed totæ tres personæ coæternæ sibi sunt, et coæquales.", "",
  [("t", "Philippians 2:6"), ("t", "John 17:5"), ("t", "Hebrews 9:14")],
  {"coined": [("coæternæ", "co-eternal")]}),
 (27, "So that in all things, as is aforesaid: the Unity in Trinity, and the Trinity in Unity is to be worshipped.",
  "Ita, ut per omnia, sicut jam supra dictum est: et Unitas in Trinitate, et Trinitas in Unitate, veneranda sit.", "",
  [("t", "Matthew 28:19"), ("t", "Revelation 4:8"),
   ("t", "Isaiah 6:3", "The church has long heard the three “Holy”s as the Trinity; the verse itself does not say so.")],
  {"coined": [("Trinitate", "Trinity")]}),
 (28, "He therefore that will be saved: must thus think of the Trinity.",
  "Qui vult ergo salvus esse, ita de Trinitate sentiat.", "salv",
  [("t", "John 17:3"), ("t", "1 John 2:23"), ("t", "2 John 1:9")],
  {"note": WARN, "coined": [("Trinitate", "Trinity")]}),
 (29, "Furthermore it is necessary to everlasting salvation: that he also believe rightly the Incarnation of our Lord Jesus Christ.",
  "Sed necessarium est ad æternam salutem: ut incarnationem quoque Domini nostri Jesu Christi fideliter credat.", "salut domin iesu christ cred",
  [("t", "1 John 4:2"), ("t", "2 John 1:7"), ("t", "John 20:31")],
  {"coined": [("incarnationem", "incarnation")]}),
 (30, "For the right Faith is that we believe and confess: that our Lord Jesus Christ, the Son of God, is God and Man;",
  "Est ergo fides recta, ut credamus et confiteamur: quod Dominus noster Jesus Christus Dei Filius, Deus pariter et homo est;", "cred confit christ fili homo",
  [("w", "Romans 10:9"), ("w", "Matthew 16:16"), ("t", "1 Timothy 2:5"), ("t", "John 1:14")], {}),
 (31, "God, of the Substance of the Father, begotten before the worlds: and Man, of the Substance of his Mother, born in the world;",
  "Deus est ex substantia Patris, ante secula genitus: et homo ex substantia matris, in seculo natus.", "saecul genit",
  [("t", "John 1:1"), ("w", "Hebrews 1:2"), ("t", "Galatians 4:4"), ("t", "Luke 2:7"), ("f", "Micah 5:2")], {}),
 (32, "Perfect God, and Perfect Man: of a reasonable soul and human flesh subsisting;",
  "Perfectus Deus: perfectus homo, ex anima rationali et humana carne subsistens.", "anima carn caro",
  [("t", "Colossians 2:9"), ("t", "Hebrews 2:17"), ("w", "Matthew 26:38"), ("t", "Luke 24:39"), ("t", "John 1:14")], {}),
 (33, "Equal to the Father, as touching his Godhead: and inferior to the Father, as touching his Manhood.",
  "Æqualis Patri secundum divinitatem: minor Patre secundum humanitatem.", "aequal patr",
  [("w", "Philippians 2:6"), ("t", "John 14:28", "“My Father is greater than I”: the creed reads it of his manhood."), ("t", "John 5:18"), ("t", "Hebrews 2:9")], {}),
 (34, "Who although he be God and Man: yet he is not two, but one Christ;",
  "Qui licet Deus sit et homo; non duo tamen, sed unus est Christus.", "",
  [("t", "1 Timothy 2:5"), ("t", "John 1:14"), ("t", "Romans 9:5"), ("t", "1 Corinthians 8:6")], {}),
 (35, "One, not by conversion of the Godhead into flesh: but by taking of the Manhood into God;",
  "Unus autem, non conversione divinitatis in carnem: sed assumptione humanitatis in Deum.", "",
  [("t", "Philippians 2:7"), ("t", "Hebrews 2:16"), ("t", "John 1:14")], {}),
 (36, "One altogether, not by confusion of Substance: but by unity of Person.",
  "Unus omnino; non confusione substantiæ: sed unitate personæ.", "",
  [("t", "Colossians 2:9"), ("t", "Romans 1:3-4"),
   ("t", "1 Timothy 3:16", "“God was manifest in the flesh” follows the later manuscripts; the oldest read “He who was manifested”.")], {}),
 (37, "For as the reasonable soul and flesh is one man: so God and Man is one Christ.",
  "Nam sicut anima rationalis et caro unus est homo: ita Deus et homo unus est Christus.", "",
  [("t", "1 Timothy 2:5"), ("t", "Genesis 2:7"), ("t", "1 Thessalonians 5:23")], {}),
 (38, "Who suffered for our salvation: descended into hell, rose again the third day from the dead.",
  "Qui passus est pro nostra salute: descendit ad inferos: tertia die resurrexit a mortuis.", "pass pati salut descend infer terti resurr resurg mortu",
  [("w", "Luke 24:46"), ("w", "1 Corinthians 15:4"), ("w", "Ephesians 4:9"), ("w", "Hebrews 2:10"), ("t", "1 Peter 3:19"), ("f", "Psalms 16:10")],
  {"disputed": True, "disp_en": "descended into hell", "disp_orig": "descendit ad inferos", "note": DESCENT}),
 (39, "He ascended into heaven, he sitteth on the right hand of the Father, God Almighty: from whence he shall come to judge the quick and the dead.",
  "Ascendit ad cœlos: sedet ad dexteram Dei Patris omnipotentis. Inde venturus est judicare vivos et mortuos.", "ascend sede sedit dexter dextr ventur iudic vivos vivor mortu",
  [("w", "Ephesians 4:10"), ("w", "Colossians 3:1"), ("w", "2 Timothy 4:1"), ("w", "Acts 10:42"), ("t", "Acts 1:11"), ("f", "Psalms 110:1")], {}),
 (40, "At whose coming all men shall rise again with their bodies: and shall give account for their own works.",
  "Ad cujus adventum omnes homines resurgere habent cum corporibus suis; et reddituri sunt de factis propriis rationem.", "advent resurg corpor reddi ration",
  [("w", "Romans 14:12"), ("w", "1 Corinthians 15:23"), ("w", "Matthew 12:36"), ("t", "John 5:28"), ("t", "2 Corinthians 5:10"), ("f", "Daniel 12:2")], {}),
 (41, "And they that have done good shall go into life everlasting: and they that have done evil into everlasting fire.",
  "Et qui bona egerunt, ibunt in vitam æternam: qui vero mala, in ignem æternum.", "bona eger ibunt vita aetern mala ignem",
  [("w", "John 5:29"), ("w", "Matthew 25:46"), ("w", "Matthew 25:41"), ("f", "Daniel 12:2")],
  {"note": "Close to word for word from John 5:29 and Matthew 25:46 in the Latin Bible the creed's author read."}),
 (42, "This is the Catholick Faith: which except a man believe faithfully, he cannot be saved.",
  "Hæc est fides catholica: quam nisi quisque fideliter firmiterque crediderit, salvus esse non poterit.", "fide cred salv",
  [("t", "John 3:18"), ("t", "John 3:36"), ("t", "Hebrews 11:6"), ("t", "Acts 4:12")],
  {"note": WARN, "coined": [("catholica", "catholic")]}),
]

ARTICLES = [{"n": n, "phrases": [(str(n), en, la, stems, links, extra)],
             **({"left_out": [("Mark 16:16", "Often set beside these lines. It stands in the longer ending of Mark, which the oldest manuscripts lack.")]} if n in (2, 42) else {})}
            for n, en, la, stems, links, extra in L]

COINED_EN = {"1": ["Catholick"], "3": ["Trinity", "Catholick"], "6": ["co-eternal"], "8": ["uncreate"],
             "12": ["uncreated"], "20": ["Catholick"], "25": ["Trinity"], "26": ["co-eternal"],
             "27": ["Trinity"], "28": ["Trinity"], "29": ["Incarnation"], "42": ["Catholick"]}

# The creed's sections, for the page: (first verse, name).
SECTIONS = [(1, "The faith"), (3, "The Trinity"), (29, "Christ"), (42, "The faith")]

# Witnesses: Westminster Confession (1647) chapter.sections; An Orthodox Creed (1679) articles.
def _w(n):
    if n in (1, 2, 28, 42): return {"WCF": ["10.4", "14.1", "14.2"], "OC": ["23"]}
    if n == 29: return {"WCF": ["8.2", "10.4"], "OC": ["5", "23"]}
    if 3 <= n <= 27: return {"WCF": ["2.1", "2.2", "2.3"], "OC": ["2", "3", "4", "8"]}
    if 30 <= n <= 37: return {"WCF": ["8.2", "8.7"], "OC": ["5", "6", "7"]}
    if n in (38, 39): return {"WCF": ["8.4"], "OC": ["17"]}
    return {"WCF": ["32.2", "32.3", "33.1", "33.2"], "OC": ["49", "50"]}
WITNESS = {n: _w(n) for n in range(1, 43)}
